### ISSUE TITLE
[brcmsdk 18.x][chpset 7271]: westeros on brcmsdk 18.x 

### ISSUE THREAD

**Issue by DAMAKsabeur** [rdkcmf/westeros#10]
hello,
 I'm working on westeros integration for my board based on bcm 7271:
I have brcmsdk's 18.x (18.2 and 18.3 I have to make decision witch one to use) with kernel v4.9.x
Am i still needs wayland-egl-bnxs ?
NB: i'm now able to compile Wayland platform for vc5 core.
Best regards
Sabeur.

**Comment by DAMAKsabeur** [comment]
Hello,.
Response to my question is yes.
I use Wayland 16.0 with Wayland protocol 1.7 
Wayland-egl implemetation used is broadcom based one integrated inside sdk 18.x.
Used renderer is the standard egl.
Ps: it is also possible to use Wayland part implementation of Wayland-egl
Regards 
Sabeur.

**Comment by Power535** [comment]
What ver. brcmsdk support 7230 
and dmt 85 Hz ?
