### ISSUE TITLE
Cannot understand the difference between embedded/nested mode

### ISSUE THREAD

**Issue by Oscar0612** [rdkcmf/westeros#12]
Hi @jeffwannamaker 

  Nice to meet you, I'm running a project which uses 'pxscene' to launch embedded mode (GPU : Mali-T820 ). I have some question about westeros.

  1. I am confusing about the difference between 'nested' and 'embedded' mode. I cannot imagine the usage of these mode. Do you have some example about how to use these two mode in real situation.

  2. When I launched 'embedded mode' by the API( wstRendererEMBCreate ), I cannot understand what display I get when I called 'eglGetDisplay' (GBM Native display in westeros-gl.c or original compositor such like wayland-0 ). Because I don't see some context initialization function in westeros-render-embedded.c (e.g: eglMakeCurrent). Do I need to implement them ?

  3. I'm try to port the 'pxscene' and the GPU of my board is Mali-T820 (drm-backedand) and I find it has some problem to launch 'embedded mode'. I can launch the normal mode and WPE can run. Do the 'embedded mode' on the Mali is supported ? 

  
  Thanks a lot.
  Best Regards,
  Oscar

**Comment by jeffwannamaker** [comment]
Hi Oscar,

Wayland nested composition is where one compositor acts as the client of another compositor.  For instance one Wayland compositor is created as a normal compositor that displays its output frames to the screen with display name “display0”.  A second Wayland compositor is created as a nested compositor with the display name “display1”.  A Wayland client application can then connect to “display1” and receive user input and render its UI.  The surfaces rendered by this client will pass to the nested compositor running “display1” and as new surfaces arrive from its clients it will render output frames consisting of the composition of all clients.  Instead displaying its output frame to the screen, it is passed as a client surface to “display0”.  The compositor running “display0” will render output frames as it receives updates from its clients and these output frames will be
displayed on the screen.

A real world example of the use of nest composition is with the WPE web browser (https://github.com/WebPlatformForEmbedded). It’s design uses a central process that receives user input and separate process for each web page.  It can be configured to use a Westeros backend where its central process creates a nested display that connects to a master compositor that displays to the screen.  The processes for each web page connect to the one nested display and the nested display distributes user input to the web page in focus.

In embedded composition an application uses Westeros API’s to create an embedded Wayland compositor instance with a given display name.  This compositor instance is available to accept connections from Wayland client apps just like any other Wayland display.  The embedded compositor instance doesn’t display its composited output frames to the display but instead makes them available to the application that created the display to use as textures within the applications UI.  This facilitates the inclusion of the UI of other applications into the UI of the application creating the embedded compositor.  An application can create multiple embedded compositor displays.

In pxscene, when a node of type “wayland” is used, it creates an embedded Wayland display and launches an application to connect to it.  The UI of the launched application is displayed as an element in the pxscene scene graph and can be manipulated and animated like any other element.

The embedded compositor instance will render using the GLES/EGL context created by the application.  So before creating an embedded display the application needs to establish an GLES/EGL context.  In the case pxscene, the GLES/EGL context is the one created by pxscene for its scene rendering.  It’s “wayland” nodes create embedded compositor instances using that GLES/EGL context (see pxWayland.cpp in pxscene).  For another example of embedded composition, look at the Westeros reference compositor: westeros-main.cpp

Yes, pxscene and embedded composition can work on devices using Mali GPU.  If the GLES/EGL/wayland-egl implementation used is provided by Mali, which would normally be the case, there can be limitations like only being able to create a single embedded compositor at a time within pxscene.  Also Mali code does not support nested composition.  In some devices Mesa can be used in place of Mali which avoids these issues.

Thanks, Jeff

**Comment by Oscar0612** [comment]
Hi @jeffwannamaker 

   Thanks for your quick response and very excellent explanation. It really helps me a lot to understand. I have another question about embedded mode and pxscene. Let me describe my question in detail.

   I launch pxscene and use “westeros_test” as my sample program.  When I launch “westeros_test” by pxscene, nothing shows onto screen (black screen).  I trace the code found something weird. After FBO pass to embedded compositor using WstCompositorComposeEmbedded in pxWayland.cpp. I step into Mali source code and found that it failed in glEGLImageTargetTexture2DOES.  The texture cannot be filled into the buffer which created by eglCreateImageKHR (eglImage).

   The GPU I use is Mali-T820 (Migard-series), In Migard-series, it separated the wayland library into wayland-client and wayland-server(libmali-client.so , libmali-server.so). The drm backend load wayland-server library and the pxscene (wayland-client) load the wayland-client library. In two library structure, glEGLImageTargetTexture2DOES shows that it cannot get EGL context. I tried to fill the red    color before the buffer return to pxscene. The screen shows the red color successfully.

   I tried to combine these two wayland library into one library, but it still failed in  glEGLImageTargetTexture2DOES. 
   
   Do you have any idea or recommendation ? 

Thanks,
Best Regards,
Oscar

**Comment by jeffwannamaker** [comment]
Hi Oscar,

That’s interesting.  I don’t know if I have used a Midgard-series.  I have a device with a Bifrost-series and embedded composition within pxscene works with it.

Thanks, Jeff

**Comment by Oscar0612** [comment]
Hi Jeff,

  I found that ‘eglGetDisplay(EGL_DEFAULT_DISPLAY)’ in westeros-render-embedded.cpp which use westeros-gl.cpp implement. After I replace it with Mali implement, pxscene can work. 

Thanks for your advice. 


Thanks,
Best Regards,
Oscar
